[project]
name = "SqueakPoseStudio"
version = "0.2.0"
description = "Tools for small-animal pose estimation, tracking, and behavioral analysis. Built for reproducibility, rapid prototyping, and seamless integration into research pipelines."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "David Haggerty", email = "david.haggerty@nih.gov" },
    { name = "Caleb Darden", email = "caleb.darden@nih.gov" },
    { name = "David Lovinger", email = "lovindav@willco.niaaa.nih.gov" },
]

dependencies = [
    "clip",
    "hdbscan>=0.8.41",
    "iprogress>=0.4",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "lightly-train>=0.14.0",
    "oneeurofilter>=0.2.1",
    "pandas>=2.3.3",
    "pyqt6>=6.11.0",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "timm>=1.0.24",
    "torch>=2.10.0",
    "torchvision",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.233",
    "umap-learn>=0.5.11",
]

[dependency-groups]
test = [
    "pyqt6>=6.11.0",
    "pyyaml>=6.0.2",
]

[tool.uv]
torch-backend = "auto"

[tool.uv.sources]
clip = { git = "https://github.com/ultralytics/CLIP/"}