[project]
name = "SqueakPoseStudio"
version = "0.2.0"
description = "Tools for small-animal pose estimation, tracking, and behavioral analysis. Built for reproducibility, rapid prototyping, and seamless integration into research pipelines."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "David Haggerty", email = "david.haggerty@nih.gov" },
    { name = "Caleb Darden", email = "caleb.darden@nih.gov" },
    { name = "David Lovinger", email = "lovindav@willco.niaaa.nih.gov" },
]

dependencies = [
    "clip",
    "hdbscan>=0.8.44",
    "iprogress>=0.4",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "lightly-train>=0.17.0",
    "matplotlib>=3.11.1",
    "numba>=0.66.0",
    "numpy>=2.4.6",
    "oneeurofilter>=0.2.1",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pyqt6>=6.11.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "timm>=1.0.28",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
    "ultralytics>=8.4.114",
    "umap-learn>=0.5.12",
]

[dependency-groups]
test = [
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "oneeurofilter>=0.2.1",
    "pandas>=3.0.5",
    "pyqt6>=6.11.0",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
]

[tool.uv]
torch-backend = "auto"

[tool.uv.sources]
clip = { git = "https://github.com/ultralytics/CLIP/"}
